version: '3'

tasks:
  build:
    cmds:
      - echo "Building Sonr Highway Node"
      - go build -o highwayd main.go

  run:
    cmds:
      - echo "Running Sonr Highway Node"
      - go run main.go

  buf:
    dir: proto
    cmds:
      - echo "Generating and Pushing Protobufs"
      - buf mod update
      - buf build
      - buf push
