name: Build_and_test_highway

on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]

jobs:

  build_and_test:
    runs-on: ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: sonr-io/sonr
          fetch-depth: 0
      - uses: actions/setup-go@v2

      - name: Issue Release Assets
        uses: tendermint/starport/actions/cli@develop
        with:
          args: chain build --release
